# Generated by Django 2.0.4 on 2018-04-18 08:49

from django.db import migrations, models
import django.db.models.deletion

from nimodipine.models import Intervention


def drop_all_interventions(*args, **kw):
    Intervention.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('nimodipine', '0002_intervention_hits'),
    ]

    operations = [
        migrations.RunPython(drop_all_interventions),
        migrations.CreateModel(
            name='InterventionContact',
            fields=[
                ('practice_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, max_length=100, null=True)),
                ('address4', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nimodipine.InterventionContact'),
            preserve_default=False,
        ),
    ]
