# Generated by Django 2.0.4 on 2018-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimodipine', '0008_maillog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maillog',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='intervention',
            name='receipt',
            field=models.NullBooleanField(),
        ),
    ]
