# Generated by Django 2.0.4 on 2018-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antibioticsrct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
