# Generated by Django 2.0.4 on 2018-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antibioticsrct', '0006_interventioncontact_survey_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interventioncontact',
            name='normalised_fax',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
