# Generated by Django 2.0.4 on 2018-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antibioticsrct', '0010_auto_20180503_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
