# Generated by Django 2.0.4 on 2018-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antibioticsrct', '0011_intervention_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='maillog',
            table='frontend_maillog',
        ),
    ]
